return {
	"m4xshen/hardtime.nvim",
	opts = {
		disabled_keys = {
			["<Up>"] = {},
			["<Down>"] = {},
			["<Left>"] = {},
			["<Right>"] = {},
		},
		disable_mouse = false,
		disabled_filetypes = {
			"qf",
			"netrw",
			"NvimTree",
			"lazy",
			"mason",
			"alpha",
			"neo-tree",
			"toggleterm",
			"TelescopePrompt",
			"Trouble",
			"Outline",
			"ToggleTerm",
			"help",
			"dap-repl",
			"dapui_scopes",
			"dapui_breakpoints",
			"dapui_stacks",
			"dapui_watches",
			"dapui_console",
		},
	},
}
